<Project Sdk="Microsoft.NET.Sdk.WebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <RunAOTCompilation>true</RunAOTCompilation>
    <InvariantGlobalization>true</InvariantGlobalization>
    <InvariantTimezone>true</InvariantTimezone>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <WasmEmitSourceMap>false</WasmEmitSourceMap>
    <WasmNativeDebugSymbols>false</WasmNativeDebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Avalonia.Themes.Fluent" />
    <TrimmerRootAssembly Include="Avalonia.Base" />
    <TrimmerRootAssembly Include="Avalonia.Controls" />
    <TrimmerRootAssembly Include="Avalonia.Markup" />
    <TrimmerRootAssembly Include="Avalonia.Markup.Xaml" />
    <TrimmerRootAssembly Include="Avalonia.Markup.Xaml.Loader" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XamlPlayground\XamlPlayground.csproj" />
  </ItemGroup>

</Project>
