name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 10.0.100

    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Publish .NET Project
      run: dotnet publish src/XamlPlayground.Browser/XamlPlayground.Browser.csproj -c Release --nologo

    - name: Change base-tag in index.html from / to XamlPlayground
      run: sed -i 's/<base href="\/" \/>/<base href="\/XamlPlayground\/" \/>/g' src/XamlPlayground.Browser/bin/Release/net10.0-browser/publish/wwwroot/index.html

    - name: copy index.html to 404.html
      run: cp src/XamlPlayground.Browser/bin/Release/net10.0-browser/publish/wwwroot/index.html src/XamlPlayground.Browser/bin/Release/net10.0-browser/publish/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch src/XamlPlayground.Browser/bin/Release/net10.0-browser/publish/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: src/XamlPlayground.Browser/bin/Release/net10.0-browser/publish/wwwroot
